output:
  # Writes to stdout
  # All program status logging will be moved to stderr

  RabbitMQ:
    enabled: true
    address: volatility.cs.umd.edu
    port: 5672
    username: admin
    password: password
    exchange: syscalls
    ssl: false

  #stdout:
  # enabled: false

    # Total number of attempts to write a line before considering giving up
    # If a write fails go-audit will sleep for 1 second before retrying
    # Default is 3
  #  attempts: 2

rules:
  # Watch all 64 bit program executions
  - -a exit,always -S all
  # Watch all 32 bit program executions
  #- -a exit,always -F arch=b32 -S all
  # Enable kernel auditing (required if not done via the "audit" kernel boot parameter)
  # You can also use this to lock the rules. Locking requires a reboot to modify the ruleset.
  # This should be the last rule in the chain.